### ISSUE TITLE
[Question] Add Shell Integration (right click menu on file)

### ISSUE THREAD

**Issue by VegethB** [fsinapsi/avinaptic2#1]
Hi, I don't find the command to give to the command line to say to open the file where I just did right click analyze with avinaptic2. Let me explain, from Windwos' Regedit.exe you can manually add a context entry such as that of mediainfo which, by right clicking on an .mp4, opens mediainfo with that .mp4. The problem is that I can't find the command for the avinaptic2 gui.exe version that causes it to open the newly selected file.
My version:
![image](https://user-images.githubusercontent.com/17975351/85904462-16812400-b809-11ea-892e-1dbfc89a7682.png)
MediainfoXP:
![image](https://user-images.githubusercontent.com/17975351/85904506-33b5f280-b809-11ea-9351-b5d5b974a934.png)

![image](https://user-images.githubusercontent.com/17975351/85904545-4c260d00-b809-11ea-810a-2b47cd68aac9.png)
The result is that doing open with avinaptic opens me as if I were using mediainfo / mediainfoXP / and similar programs.
Sorry for my english.

EDIT1:
![image](https://user-images.githubusercontent.com/17975351/85905383-8bedf400-b80b-11ea-9285-13fd42f3729a.png)
ok, just remove -cl ... pity that now by mistake saying:
![image](https://user-images.githubusercontent.com/17975351/85905454-bc359280-b80b-11ea-9580-28bc284e615c.png) e
![image](https://user-images.githubusercontent.com/17975351/85905469-c6f02780-b80b-11ea-8d92-cfeff6a7e605.png)
Also create an avinaptic.cfg in the folder of the file that you decide to analyze.
If it weren't for the .cfg I'd be content with it ...

**Comment by fsinapsi** [comment]
Ciao zFerry98, ti rispondo in italiano perché mi pare che tu sia italiano.
Per il problema del file di configurazione, potresti provare questa opzione: "--cfg=D:\Programmi\avinaptic2\avinaptic.cfg"
Fammi sapere.

**Comment by VegethB** [comment]
> Ciao zFerry98, ti rispondo in italiano perché mi pare che tu sia italiano.
> Per il problema del file di configurazione, potresti provare questa opzione: "--cfg=D:\Programmi\avinaptic2\avinaptic.cfg"
> Fammi sapere.

Solitamente scrivo (anche se male) in inglese perché su tipo il 90% dei siti/forum si sono sempre lamentati se scrivevi nella tua lingua.
Per errore del cfg risolve 👍. Errore di libmagic rimane tale quale 🙃. Probabilmente ci vorrebbe un comando che faccia capire la cartella di esecuzione con tutto. Purtroppo non sono esperto di Shell commands.

**Comment by fsinapsi** [comment]
> Errore di libmagic rimane tale quale

nella pagina di [avinaptic](http://fsinapsi.altervista.org/code/avinaptic/index.html) ho messo uno zip ([avinaptic2-temp.zip](http://fsinapsi.altervista.org/code/avinaptic/avinaptic2-temp.zip)) che contiene i due eseguibili per windows 32-bit (avinaptic2.exe, avinaptic2-cli.exe).
Se hai voglia, doresti provare a sostituirli ai due omonimi file (che credo tu abbia nella cartella D:\Programmi\avinaptic2).
L'opzione da usare per il problema del magic è "--mgc=D:\Programmi\avinaptic2\magic.mgc"
Se mi confermi, farò un nuovo zip con dll e tutto il resto.
Ciao e grazie

**Comment by VegethB** [comment]
![image](https://user-images.githubusercontent.com/17975351/85945339-6bbe5200-b93d-11ea-9365-6b486222d9ec.png)
Entrambi i .exe danno questo errore.
Invece "--mgc=" dice che non è una opzione valida (come se cfg non fosse il vero switch per dirgli dove si trova cfg)
![image](https://user-images.githubusercontent.com/17975351/85945531-cb692d00-b93e-11ea-8a6a-7c852baf5331.png)

![image](https://user-images.githubusercontent.com/17975351/85945433-074fc280-b93e-11ea-933f-ffe7a477c730.png)
Sia che {  "D:\Programmi\avinaptic2\avinaptic2.exe --cfg=D:\Programmi\avinaptic2\avinaptic.cfg --mgc=D:\Programmi\avinaptic2\magic.mgc "%1  }  o  {  D:\Programmi\avinaptic2\avinaptic2.exe --mgc=D:\Programmi\avinaptic2\magic.mgc "%1"  } stesso errore.

Aggiungendo manualmente Libgnurx-0.dll riporta questo errore: 
![image](https://user-images.githubusercontent.com/17975351/85945630-64984380-b93f-11ea-96aa-fb0c81212e22.png) Solitamente è perché non viene eseguito con privilegi amministrativi (ovviamente ho fatto due prove con e senza privilegi e stesso errore entrambi)

**Comment by fsinapsi** [comment]
Prova a scaricare [questa versione di libgnurx](http://fsinapsi.altervista.org/gnurx.zip), cioè togli Libgnurx-0.dll che hai messo e metti nella cartella D:\Programmi\avinaptic2 la dll contenuta in gnurx.zip.
Poi prova a usare entrambe le opzioni (--cfg e --mgc), ma solo con il nuovo avinaptic2.exe.
Quello che ti dice che --mgc non è un'opzione valida è il vecchio avinaptic2.exe di 9 anni fa, giusto?
(In tal caso è normale, visto che l'ho messo stamattina).
Mi piacerebbe ricompilare tutto a 64 bit per windows e meglio di come adesso, ma purtroppo l'unico sistema windows che ho è una vecchissima mv Virtualbox win xp 32 bit, su cui una decina di anni fa misi MinGW e un po' di librerie precompilate. Non è stato facile ricompilare avinaptic dopo tanti anni. Andrebbe rifatto tutto, però non avendo altri windows non saprei come fare. Per il futuro credo che mi limiterò ad aggiornare i sorgenti, sperando che qualcuno abbia voglia di compilare...

**Comment by VegethB** [comment]
> Poi prova a usare entrambe le opzioni (--cfg e --mgc), ma solo con il nuovo avinaptic2.exe.
> Quello che ti dice che --mgc non è un'opzione valida è il vecchio avinaptic2.exe di 9 anni fa, giusto?
Sì, perché quello nuovo non partiva neanche con la .dll che ho trovato in rete.

Confermo che ora funziona tramite Tasto destro 👍👍👍👍

> Mi piacerebbe ricompilare tutto a 64 bit per windows e meglio di come adesso, ma purtroppo l'unico sistema windows che ho è una vecchissima mv Virtualbox win xp 32 bit, su cui una decina di anni fa misi MinGW e un po' di librerie precompilate. Non è stato facile ricompilare avinaptic dopo tanti anni. Andrebbe rifatto tutto, però non avendo altri windows non saprei come fare. Per il futuro credo che mi limiterò ad aggiornare i sorgenti, sperando che qualcuno abbia voglia di compilare...

Purtroppo di programmazione in generale non sono riuscito a starci dietro. Finché si deve solo compilare un progetto in qualche modo riesco. Non saprei se Docker può funzionare https://devblogs.microsoft.com/cppblog/build-c-applications-in-a-linux-docker-container-with-visual-studio/ ovviamente mi rendo conto che se vuoi compilare a x64 devi avere una macchina x64.  
Comunque, ti ringrazio per avermi aiutato con questa cosuccia extra del tasto destro.

**Comment by fsinapsi** [comment]
> Comunque, ti ringrazio per avermi aiutato con questa cosuccia extra del tasto destro.

grazie a te, mi hai dato occasione di vedere com'è la situazione nella vecchia macchina virtuale win (situazione abbastanza tragica).
Il problema con gnurx si è presentato perché a suo tempo ebbi bisogno di aggiungere un minimo di supporto alle espressioni regolari, e stamattina è venuto fuori che per compilare il compilatore (e quindi qualsiasi altro programma) ho dovuto aggiungere "-lregex" (ma solo su MinGW perché in linux non serve, e non ho idea ma forse al giorno d'oggi non serve nemmeno su MinGW, ed è per questo che vorrei aggiornare tutto).
Quindi, quando ho compilato avinaptic2.exe, anche se avinaptic2 non usa espressioni regolari, l'eseguibile necessita comunque di quella dll. Io me ne accorgo difficilmente di questi requisiti, perché da msys quelle dll vengono comunque trovate...
Un'altra cosa che mi piacerebbe fare è di sostituire le chiamate a gtk2 con [iup](http://webserver2.tecgraf.puc-rio.br/iup/), che uso già da anni. Non dovrebbe essere troppo impegnativo. Il vantaggio è che potrei fare uno zip con avinaptic2.exe e pochissime dll rispetto alle attuali (l'aspetto cambierebbe un po', perché gtk2 sparirebbe e iup usa direttamente le api windows). Altro vantaggio è che sotto linux, avinaptic2 userebbe gtk3, per chi preferisce.
Ciao e ancora grazie. Che devo fare adesso, "close and comment"? Per ora lascio aperto, poi vedrò...

**Comment by VegethB** [comment]
Sì, siccome la mia richiesta era far funzionare integrazione shell e non di aggiungere al programma funzioni o bug che necessitavano dei fix, si chiude. Per semplicità nel readme aggiungi il processo per mettere questa features oppure implementa nelle build future del programma una cosa simile a questa: 
![image](https://user-images.githubusercontent.com/17975351/85949308-4ee24880-b956-11ea-8315-46ae990d3125.png)
Aggiungi "Apri con Mediainfo" al menu contestuale. 👍
