### ISSUE TITLE
feature request - provide some progress indicator to avinaptic-cli

### ISSUE THREAD

**Issue by git-mf** [fsinapsi/avinaptic2#2]
hi all,
first i would like to thank you for maintaining (still) avinaptic, as i use the tool almost everyday for my personal stuff.

i actually wrote a wrapper around the cli version (windows), since it is _very_ silent i read the process stats to be able to keep track of the parsing progress, which is, i admit, not that elegant.

is it possible to provide avinaptic2-cli some intermediate output while in the parsing process ?

**Comment by fsinapsi** [comment]
Hi, I added the --show-progress option which prints messages like "progress: 0.2% \ r progress: 1.3% \ r ..." on the standard error. Hope this helps.

**Comment by git-mf** [comment]
works like a charm, thanks a lot !
