### ISSUE TITLE
Report coherency...?

### ISSUE THREAD

**Issue by eblanca** [fsinapsi/avinaptic2#5]
I have this report created by avinaptic2 (built a few days ago) where at statement 45 (Video track info block) I see
```
Pixel aspect ratio: 333:320 = 1.040625
```

instead at statement 117 (Video bitstream detail block) there is
```
  Aspect ratio: Square pixels
```

I think both information can't stand together, or can they? is this expected?

[movie.mkv.report.txt](https://github.com/fsinapsi/avinaptic2/files/9057420/movie.mkv.report.txt)

**Comment by fsinapsi** [comment]
> I think both information can't stand together, or can they? is this expected?

yes, both information can stand together ("Aspect ratio: Square pixels" is stored in a video bitstream, "Pixel aspect ratio: 333:320" is stored in the container)

**Comment by eblanca** [comment]
ok, thanks!
